### PR TITLE
Rating Vote Count

### PR DESCRIPTION
**Pull request by Danwakeem**
### Description
- Added the vote count from the IMDB to the Movies Class.
- Added `.travis.yml` file to [automate the testing process](http://travis-ci.org/) :)

#### Related issues

- connect to mhsjlw/imdb#24

### Checklist

- [x] New tests added or existing tests modified to cover all changes

### CODE REVIEW

**Comment by Danwakeem** [comment]
Not sure if you are actually interested in Travis-CI but thought it might be something cool to look into

**Comment by mhsjlw** [comment]
Thanks for this pull request! I'll try to get it merged as soon as possible. I usually don't use Travis and am more comfortable using CircleCI. I've been meaning to set it up.

**Comment by Danwakeem** [comment]
Ahh okay no problem, I will go ahead and remove the Travis file from this commit.

**Comment by mhsjlw** [comment]
I'll get CI setup right now. Thanks again for the changes.

**Pull request merged**
